export const FETCH_WEATHER = "APP/FETCH_WEATHER";
export const FETCH_SEARCH_WEATHER = "CITY_PAGE/FETCH_SEARCH_WEATHER";

export const SET_INPUT = "SET_INPUT";
export const CLEAN_INPUT = "CLEAN_INPUT";
export const CLEAN_TOWN = "CLEAN_TOWN";
export const HIDE_LOADER = "APP/HIDE_LOADER";
